name: Build & Lint

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.1
        with:
          node-version: "14.x"
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6"
      - run: gem install bundler:2.1.4
      - run: bundle install
      - run: ruby Sources/fetch_app_status.rb